#!/usr/bin/env python3
"""vector.py — Local vector search over memories via Chroma + sentence-transformers (BGE-M3).

First run: builds the index from all memories in MEMORY_DIR.
Subsequent runs: re-indexes only modified memories (mtime-based).

Paths resolved via `_paths.py` — project-agnostic. Override with env vars:
    CORTEX_PROJECT_ID / CORTEX_MEMORY_DIR / CORTEX_INDEX_DIR

Usage:
    python scripts/vector.py index                       # (re)build the index
    python scripts/vector.py search "tactical combat"    # top-5 relevant memories
    python scripts/vector.py search --k 10 "facing"      # top-10
    python scripts/vector.py clear                       # wipe the index
"""
import argparse
import datetime
import sys
from pathlib import Path

import chromadb
from chromadb.utils import embedding_functions
import yaml

from _paths import MEMORY_DIR, INDEX_DIR, PROJECT_ID

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


# SOTA 2024 multilingual model — best quality on non-English, 100+ languages.
# BGE-M3 (BAAI): ~1 GB but local latency ~30ms, native FR/ES/DE/etc support.
# Auto-downloaded on first run (sentence-transformers cache).
EMBED_MODEL = "BAAI/bge-m3"

# Project-aware collection name (avoids collisions if multiple projects share Chroma)
COLLECTION_NAME = f"cortex_{PROJECT_ID}".replace("-", "_")[:60]


def _fm_to_str(v: object) -> str:
    """Defensive cast: yaml.safe_load parses unquoted dates as datetime.date."""
    if isinstance(v, datetime.datetime):
        return v.isoformat()
    if isinstance(v, datetime.date):
        return v.isoformat()
    return str(v) if v is not None else ""


def get_embedder():
    return embedding_functions.SentenceTransformerEmbeddingFunction(model_name=EMBED_MODEL)


def get_client():
    INDEX_DIR.mkdir(parents=True, exist_ok=True)
    return chromadb.PersistentClient(path=str(INDEX_DIR))


def get_collection(client):
    return client.get_or_create_collection(
        name=COLLECTION_NAME,
        metadata={"hnsw:space": "cosine"},
        embedding_function=get_embedder(),
    )


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Return (frontmatter_dict, body). Frontmatter is {} if absent."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}, text
    try:
        fm = yaml.safe_load(text[4:end]) or {}
    except yaml.YAMLError:
        fm = {}
    fm = _normalize_frontmatter(fm)
    body = text[end + 5:].strip()
    return fm, body


def _normalize_frontmatter(fm: dict) -> dict:
    """Promote fields from `metadata:` wrapping to top-level (Claude Code auto-memory compat).

    See rebuild_index.py for the full rationale. Without this, memories created via
    the Write tool (which auto-wraps fields under `metadata:`) would be indexed with
    empty triggers/type/priority and rank poorly in vector search.
    """
    metadata = fm.get("metadata")
    if isinstance(metadata, dict):
        for key, value in metadata.items():
            fm.setdefault(key, value)
    return fm


def build_indexed_text(fm: dict, body: str) -> str:
    """Compose indexed text, boosting metadata weight.

    Anti-English-bias strategy:
    - Triggers repeated 2x at top (semantic boost on explicit keywords)
    - Name + description in priority position (strong non-English signal)
    - Body capped at 3000 chars (frontmatter has higher priority)
    """
    parts = []
    triggers = fm.get("triggers") or []
    if triggers:
        trig_str = ", ".join(_fm_to_str(t) for t in triggers)
        parts.append(f"Keywords: {trig_str}")
        parts.append(f"Topics: {trig_str}")  # repetition = boost
    if fm.get("name"):
        parts.append(f"Title: {fm['name']}")
    if fm.get("description"):
        parts.append(f"Description: {fm['description']}")
    parts.append(body[:3000])
    return "\n\n".join(parts)


def index_all(force_rebuild: bool = False):
    if not MEMORY_DIR.exists():
        print(f"⚠️ MEMORY_DIR does not exist: {MEMORY_DIR}")
        print("   Create the directory first + at least one memory with frontmatter.")
        return

    client = get_client()
    if force_rebuild:
        try:
            client.delete_collection(COLLECTION_NAME)
        except Exception:
            pass
    collection = get_collection(client)

    existing_ids = set(collection.get()["ids"])

    docs, metas, ids = [], [], []
    skipped = 0
    for path in sorted(MEMORY_DIR.glob("*.md")):
        # MEMORY.md + sub-index files are auto-generated by rebuild_index.py —
        # no own content to index. MEMORY_PROTOCOL.md contains usage rules —
        # indexed (searchable via "audit memory", "protocol", etc.).
        if path.name in ("MEMORY.md", "MEMORY_BACKLOG.md", "MEMORY_REFERENCES.md"):
            continue
        if path.name.startswith("_"):
            continue
        content = path.read_text(encoding="utf-8")
        fm, body = parse_frontmatter(content)

        if not body and not fm:
            skipped += 1
            continue

        indexed_text = build_indexed_text(fm, body)

        mtime = int(path.stat().st_mtime)
        doc_id = f"{path.name}:{mtime}"
        if doc_id in existing_ids:
            continue  # already indexed at this version

        # Purge older versions of this memory (other mtimes)
        old_ids = [i for i in existing_ids if i.startswith(f"{path.name}:")]
        if old_ids:
            collection.delete(ids=old_ids)

        # Enriched metadata for decay + priority boost at search time
        priority = _fm_to_str(fm.get("priority", "normal")).lower()
        last_verified = _fm_to_str(fm.get("last_verified")) or ""

        docs.append(indexed_text[:4000])
        metas.append({
            "file": path.name,
            "mtime": mtime,
            "type": fm.get("type", "unknown"),
            "priority": priority,
            "last_verified": last_verified,
        })
        ids.append(doc_id)

    if docs:
        collection.add(documents=docs, metadatas=metas, ids=ids)
        print(f"✅ {len(docs)} memory(ies) (re)indexed")
    else:
        print("✅ Index up to date, nothing to do")
    if skipped:
        print(f"   ({skipped} skipped — empty content or archive)")
    print(f"   Total index: {collection.count()} documents · collection={COLLECTION_NAME}")


PRIORITY_MULT = {
    "critical": 1.10,
    "high": 1.05,
    "normal": 1.00,
    "low": 0.95,
}
DECAY_HALFLIFE_DAYS = 180  # beyond this, cap at -50% on bge_score


def _compute_final_score(bge_score: float, priority: str, last_verified: str) -> tuple[float, float, float]:
    """Returns (final_score, decay_factor, priority_mult).

    Multiplicative formula: final = bge_score * decay * priority_mult
    - decay = 1 - 0.5 * min(days_since_verified / 180, 1), 1.0 if date absent/invalid
    - priority_mult ∈ {×1.10 critical, ×1.05 high, ×1.00 normal, ×0.95 low}

    Multiplicative vs additive: a boost amplifies bge relevance, doesn't compensate.
    A critical memory at bge 0.44 cannot exceed a normal memory at bge 0.55
    (0.44×1.10=0.48 < 0.55). Eliminates parasitic boosts from additive +0.10.
    """
    decay = 1.0
    if last_verified:
        try:
            if isinstance(last_verified, (datetime.date, datetime.datetime)):
                dt = last_verified if isinstance(last_verified, datetime.date) else last_verified.date()
            else:
                dt = datetime.date.fromisoformat(str(last_verified)[:10])
            days = (datetime.date.today() - dt).days
            if days > 0:
                decay = 1 - 0.5 * min(days / DECAY_HALFLIFE_DAYS, 1)
        except (ValueError, AttributeError):
            pass

    mult = PRIORITY_MULT.get((priority or "normal").lower(), 1.0)
    final = bge_score * decay * mult
    return final, decay, mult


def rank(query: str, k: int = 5, raw: bool = False) -> list[dict]:
    """Programmatic API: returns top-k ranked memories.

    Each entry = dict {file, final, bge, decay, mult, priority, last_verified, first_line}.
    """
    client = get_client()
    collection = get_collection(client)
    if collection.count() == 0:
        return []

    fetch_k = k if raw else max(k * 2, 10)
    results = collection.query(query_texts=[query], n_results=fetch_k)
    if not results["ids"][0]:
        return []

    entries = []
    for meta, doc, dist in zip(
        results["metadatas"][0],
        results["documents"][0],
        results["distances"][0],
    ):
        bge = 1 - dist
        if raw:
            final, decay, mult = bge, 1.0, 1.0
        else:
            priority = meta.get("priority", "normal")
            last_verified = meta.get("last_verified", "")
            final, decay, mult = _compute_final_score(bge, priority, last_verified)
        entries.append({
            "file": meta["file"],
            "final": final,
            "bge": bge,
            "decay": decay,
            "mult": mult,
            "priority": meta.get("priority", "normal"),
            "last_verified": meta.get("last_verified", ""),
            "first_line": doc.split("\n", 1)[0][:80],
        })

    if not raw:
        entries.sort(key=lambda e: e["final"], reverse=True)
    return entries[:k]


def search(query: str, k: int = 5, raw: bool = False):
    entries = rank(query, k=k, raw=raw)
    if not entries:
        client = get_client()
        if get_collection(client).count() == 0:
            print("⚠️ Empty index — run `python scripts/vector.py index` first")
        else:
            print(f"No results for: {query!r}")
        return

    mode = "RAW BGE" if raw else "decay × priority"
    print(f"## Top-{k} for: {query!r}  ({mode})\n")
    for i, e in enumerate(entries, 1):
        if raw:
            print(f"{i}. **{e['file']}** (bge={e['bge']:.2f})")
        else:
            lv = e["last_verified"] or "?"
            pr = e["priority"] or "normal"
            print(f"{i}. **{e['file']}** (final={e['final']:.2f} · bge={e['bge']:.2f} · decay={e['decay']:.2f} · ×{e['mult']:.2f}) [pr={pr}, lv={lv}]")
        print(f"   {e['first_line']}")
        print()


def clear():
    client = get_client()
    try:
        client.delete_collection(COLLECTION_NAME)
        print(f"✅ Index cleared (collection={COLLECTION_NAME})")
    except Exception as e:
        print(f"⚠️ Nothing to delete: {e}")


def main():
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="cmd", required=True)

    idx = sub.add_parser("index", help="(Re)build the vector index")
    idx.add_argument("--rebuild", action="store_true", help="Force full rebuild")

    srch = sub.add_parser("search", help="Semantic search")
    srch.add_argument("query", nargs="+", help="Free-form query")
    srch.add_argument("--k", type=int, default=5, help="Number of results (default: 5)")
    srch.add_argument("--raw", action="store_true", help="Disable decay + priority (pure BGE, debug)")

    sub.add_parser("clear", help="Clear the index")

    args = parser.parse_args()

    if args.cmd == "index":
        index_all(force_rebuild=args.rebuild)
    elif args.cmd == "search":
        query = " ".join(args.query)
        search(query, k=args.k, raw=args.raw)
    elif args.cmd == "clear":
        clear()


if __name__ == "__main__":
    main()
